const A='assets/nailong/';
const photo=['assets/photos/foto-1.jpeg','assets/photos/foto-2.jpeg','assets/photos/foto-3.jpeg','assets/photos/foto-4.jpeg','assets/photos/foto-5.jpeg','assets/photos/foto-6.jpeg'];
const pages=[
`<section class="page active cover"><div class="top">Untuk Yayaaaa 💗</div><div class="label">🎂 Sebuah hadiah kecil untuk...</div><h1 class="title">Ada sesuatu <span>buatmu</span></h1><p class="sub">Bukan sekadar ucapan ulang tahun. Aku bikin perjalanan kecil yang harus kamu mainkan sendiri. 💛</p><div class="hero"><img class="nailong" src="${A}slide01-cover.png"></div><div class="gift"><b>🎁 Hadiah rahasia dari aku</b><small>Sentuh tombolnya, lalu ikuti semua permainan kecilnya.</small></div><button class="start" data-next>Mulai 💗</button></section>`,
`<section class="page" data-game="flowers"><div class="top">Untuk Yayaaaa 💗</div><div class="label">01 · Hadiah pertama</div><h2 class="title">Nailong punya sesuatu <span>buatmu</span></h2><p class="sub">Kasih bunga ke Nailong dulu yaa 🌸</p><div class="hero" id="flowerGame"><div class="target"><small>Tarik bunga ke sini 💕</small></div><img id="flowerNailong" class="nailong" src="${A}slide01-sad.png"><img class="flower left dragFlower" src="${A}flower-sunflower.png"><img class="flower right dragFlower" src="${A}flower-sunflower.png"><div class="success" id="flowerSuccess">Nailong senyum karena kamu 💗</div></div><div class="instruction">🌷 Tarik kedua bunga ke Nailong.<br>Kalau dua-duanya berhasil, dia akan tersenyum.</div><button class="next" data-next id="flowerNext">Klik disini 💗</button></section>`,
`<section class="page" data-game="hearts"><div class="top">Untuk Yayaaaa 💗</div><div class="label">02 · Rahasia kecil</div><h2 class="title">Ada <span>hati</span> yang ngumpet...</h2><p class="sub">Tap semua hati yang kamu temukan. Setiap hati punya pesan dari aku.</p><div class="heart-zone" id="heartZone"><div class="toast" id="toast"></div><span class="heart" style="left:10%;top:14%">💗</span><span class="heart" style="left:70%;top:18%">💖</span><span class="heart" style="left:38%;top:42%">💘</span><span class="heart" style="left:16%;top:70%">💝</span><span class="heart" style="left:76%;top:68%">💓</span></div><div class="instruction">💗 Tap semua hati · <span id="heartCount">0/5</span></div><button class="next" data-next id="heartNext">Lanjut 💗</button></section>`,
`<section class="page" data-game="cloud"><div class="top">Untuk Yayaaaa 💗</div><div class="label">03 · Buka perlahan</div><h2 class="title">Geser <span>awan</span>-nya</h2><p class="sub">Ada pesan kecil yang sengaja aku sembunyikan di balik awan.</p><div class="cloudbox"><div class="secretmsg">💌<br><br>“Semoga setiap langkah sayang tahun ini<br>membawa semakin dekat dengan semua hal yang sayang impikan.<br>Dan semoga aku tetap ada di sampingmu,<br>menemani setiap perjalanan itu. 💗”</div><div class="cloudcover" id="cloudCover"><img src="${A}slide03-cloud.png"></div><div class="sliderhint">Geser awan ke kanan →</div></div><div class="instruction">☁️ Geser awannya sampai pesannya terlihat.</div><button class="next" data-next id="cloudNext">Lanjut 💗</button></section>`,
`<section class="page" data-game="camera"><div class="top">Untuk Yayaaaa 💗</div><div class="label">04 · Satu kilas balik</div><h2 class="title">Klik kamera,<br><span>ambil kenangan</span></h2><p class="sub" id="cameraSub">Awasss kagett yaa hahaha</p><div class="camera-card"><div class="camera" id="camera"><div class="lens"></div></div><div class="photo" id="cameraPhoto"><img src="${photo[0]}"></div></div><div class="instruction">📸 Tap kamera. Akan ada flash kecil lalu foto muncul.</div><button class="next" data-next id="cameraNext">Lanjut 💗</button><div class="flash" id="flash"></div></section>`,
`<section class="page" data-game="photos"><div class="top">Untuk Yayaaaa 💗</div><div class="label">05 · Memori kita</div><h2 class="title">Buka semua <span>kartu foto</span></h2><p class="sub">Buka satu per satu yaa. Nggak semuanya sempurna, nggak semuanya aesthetic. Nggak kerasa udah sejauh ini yeee, Semangat ya LDR nya yayakk</p><div class="cards" id="cards">${photo.map((p,i)=>`<div class="memory" data-i="${i}"><img src="${p}"></div>`).join('')}</div><div class="instruction">❤️ Tap semua kartu · <span id="photoCount">0/6</span></div><button class="next" data-next id="photoNext">Lanjut 💗</button></section>`,
`<section class="page" data-game="letter"><div class="top">Untuk Yayaaaa 💗</div><div class="label">06 · Dari aku untukmu</div><h2 class="title">Masukkan <span>surat</span> ini</h2><p class="sub">Tarik surat ke kotak. Setelah itu baru boleh dibuka.</p><div class="mail-area"><div class="mailbox"><div class="slot"></div></div><div class="letter" id="letter">💌</div></div><div class="instruction">💌 Tarik surat masuk ke kotak surat.</div><button class="next" data-next id="letterNext">Lanjut 💗</button></section>`,
`<section class="page" data-game="stars"><div class="top">Untuk Yayaaaa 💗</div><div class="label">07 · Harapan</div><h2 class="title">Sambungkan <span>bintang</span></h2><p class="sub">Tap bintang sesuai jalur love. Satu bintang, satu doa untukmu. ⭐</p><div class="starfield" id="starfield"><svg class="starline" id="starline" aria-hidden="true"></svg><span class="star" data-order="1" style="left:14%;top:32%">⭐</span><span class="star" data-order="2" style="left:29%;top:12%">⭐</span><span class="star" data-order="3" style="left:50%;top:25%">⭐</span><span class="star" data-order="4" style="left:71%;top:12%">⭐</span><span class="star" data-order="5" style="left:86%;top:32%">⭐</span><span class="star" data-order="6" style="left:50%;top:82%">⭐</span><span class="star" data-order="7" style="left:28%;top:55%">⭐</span><div class="doa">⭐ 0/7</div></div><div class="instruction">⭐ Mulai dari bintang paling kiri, ikuti jalur love sampai selesai.</div><button class="next" data-next id="starNext">Lanjut 💗</button></section>`,
`<section class="page" data-game="hug"><div class="top">Untuk Yayaaaa 💗</div><div class="label">08 · Bagian terakhir</div><h2 class="title">Ajak Nailong <span>mendekat</span> 🥺</h2><p class="sub">Tap Nailong beberapa kali sampai dia dekat dengan hati.</p><div class="hugbox"><div class="hugheart">💗</div><img class="hugdog" id="hugdog" src="${A}nailong_8.png"><div class="hugdone" id="hugdone">Peluk dulu sini 🫂💗</div></div><div class="instruction">🫂 Tap Nailong sampai dia mendekat.</div><button class="next" data-next id="hugNext">Lanjut 💗</button></section>`,
`<section class="page"><div class="top">Untuk Yayaaaa 💗</div><div class="label">09 · Untuk selamanya</div><div class="final-heart">💗</div><h2 class="title">Selamat ulang tahun,<br><span>Sayang!</span> 🎂</h2><div class="final-card"><p>Semoga di umur yang baru kamu selalu sehat, dimudahkan setiap langkahnya, dan apa pun yang kamu impikan bisa pelan-pelan tercapai.</p><p>Makasih udah nemenin aku selama 5 tahun ini, semoga lanjut periode 2 ya dan periode seterus-terusnya hehe. Semoga setelah ini masih banyak cerita, tawa, dan momen yang bisa kita lewatin bareng.</p><p><b>Aku sayang kamu, Yayakkkk. ❤️</b></p><div class="creator">Made by Lutfi</div></div><button class="replay" id="replay">💞 Putar lagi dari awal</button></section>`];
const story=document.getElementById('story');story.innerHTML=pages.join('');
const fairy=document.createElement('img');fairy.className='fairy-flyer';fairy.src=A+'fairy-nailong.png';fairy.alt='';fairy.setAttribute('aria-hidden','true');document.getElementById('app').appendChild(fairy);
let current=0;const all=[...document.querySelectorAll('.page')];
function go(n){current=Math.max(0,Math.min(all.length-1,n));all.forEach((p,i)=>p.classList.toggle('active',i===current));window.scrollTo({top:0,behavior:'smooth'});initPage(all[current])}
function initPage(p){if(p.dataset.ready)return;p.dataset.ready='1';
 if(p.dataset.game==='flowers') setupFlowers(p);if(p.dataset.game==='hearts')setupHearts(p);if(p.dataset.game==='cloud')setupCloud(p);if(p.dataset.game==='camera')setupCamera(p);if(p.dataset.game==='photos')setupPhotos(p);if(p.dataset.game==='letter')setupLetter(p);if(p.dataset.game==='stars')setupStars(p);if(p.dataset.game==='hug')setupHug(p)}
document.addEventListener('click',e=>{const n=e.target.closest('[data-next]');if(n)go(current+1)});
function drag(el,onDrop){let sx=0,sy=0,dx=0,dy=0,moving=false;const start=e=>{if(e.button!==undefined&&e.button!==0)return;moving=true;sx=e.clientX;sy=e.clientY;el.setPointerCapture?.(e.pointerId);el.classList.add('dragging');el.style.zIndex=40;};const move=e=>{if(!moving)return;dx=e.clientX-sx;dy=e.clientY-sy;el.style.transform=`translate3d(${dx}px,${dy}px,0)`;};const end=e=>{if(!moving)return;moving=false;el.releasePointerCapture?.(e.pointerId);el.classList.remove('dragging');const r=el.getBoundingClientRect();onDrop(r,()=>{dx=0;dy=0;el.style.transform=''});if(!el.dataset.got){dx=0;dy=0;el.style.transform='';el.style.zIndex='';}};el.addEventListener('pointerdown',start);el.addEventListener('pointermove',move);el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end)}
function sparkleBurst(p){const hero=p.querySelector('#flowerGame');if(!hero)return;for(let i=0;i<18;i++){const sp=document.createElement('span');sp.className='sparkle';const a=Math.random()*Math.PI*2,d=45+Math.random()*105;sp.style.setProperty('--x',Math.cos(a)*d+'px');sp.style.setProperty('--y',Math.sin(a)*d+'px');sp.style.left='50%';sp.style.top='48%';sp.style.animationDelay=(Math.random()*.12)+'s';sp.textContent=['✦','✧','⋆','⭐'][i%4];hero.appendChild(sp);setTimeout(()=>sp.remove(),1100)}}
function setupFlowers(p){let got=0;const target=p.querySelector('.target'),img=p.querySelector('#flowerNailong'),next=p.querySelector('#flowerNext'),ok=p.querySelector('#flowerSuccess');p.querySelectorAll('.dragFlower').forEach((f,i)=>{f.style.animationDelay=(i?'.7':'0')+'s';drag(f,(r,reset)=>{const t=target.getBoundingClientRect();const hit=r.right>t.left&&r.left<t.right&&r.bottom>t.top&&r.top<t.bottom;if(hit&&!f.dataset.got){f.dataset.got='1';f.classList.add('got');f.style.opacity='.18';f.style.transform='scale(.72)';f.style.pointerEvents='none';got++;if(got===2){img.classList.add('changing');setTimeout(()=>{img.src=A+'slide01-smile.png';img.classList.remove('changing');sparkleBurst(p)},180);ok.classList.add('show');next.classList.add('show')}}else if(!hit){reset();}})})}
function setupHearts(p){let n=0;const toast=p.querySelector('#toast');p.querySelectorAll('.heart').forEach((h,i)=>h.addEventListener('click',()=>{if(h.classList.contains('done'))return;h.classList.add('done');n++;toast.textContent=['Aku sayang kamu ❤️','selalu cantik 💗','udah menua aja yee 🥺','semangat berjuang yaa 💕','Selamat ulang tahun sayang 🎂'][i];const r=h.getBoundingClientRect(),z=p.querySelector('#heartZone').getBoundingClientRect();toast.style.left=r.left-z.left+r.width/2+'px';toast.style.top=r.top-z.top+'px';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3200);p.querySelector('#heartCount').textContent=n+'/5';if(n===5)p.querySelector('#heartNext').classList.add('show')}))}
function setupCloud(p){const c=p.querySelector('#cloudCover'),next=p.querySelector('#cloudNext'),box=c.parentElement;let sx=0,base=0,m=false;const move=e=>{if(!m)return;const max=box.clientWidth;const x=Math.max(0,Math.min(max,base+e.clientX-sx));c.dataset.x=x;c.style.transform=`translate3d(${x}px,0,0)`;if(x>box.clientWidth*.55)next.classList.add('show')};const end=e=>{if(!m)return;m=false;c.releasePointerCapture?.(e.pointerId)};c.addEventListener('pointerdown',e=>{m=true;sx=e.clientX;base=parseFloat(c.dataset.x||0);c.setPointerCapture?.(e.pointerId)});c.addEventListener('pointermove',move);c.addEventListener('pointerup',end);c.addEventListener('pointercancel',end)}
function setupCamera(p){p.querySelector('#camera').addEventListener('click',()=>{p.querySelector('#flash').classList.remove('go');void p.querySelector('#flash').offsetWidth;p.querySelector('#flash').classList.add('go');p.querySelector('#cameraPhoto').classList.add('show');p.querySelector('#cameraSub').textContent='cekrekkkkkk... Manisnyaa ooyyyyyy';p.querySelector('#cameraNext').classList.add('show');startMusic()})}
function setupPhotos(p){let n=0;p.querySelectorAll('.memory').forEach((x,i)=>{x.style.setProperty('--photo-bg',`url(\"${photo[i]}\")`);x.addEventListener('click',()=>{if(x.classList.contains('open'))return;x.classList.add('open');n++;p.querySelector('#photoCount').textContent=n+'/6';if(n===6)p.querySelector('#photoNext').classList.add('show')})})}
function setupLetter(p){const l=p.querySelector('#letter'),box=p.querySelector('.mailbox'),next=p.querySelector('#letterNext');drag(l,r=>{const b=box.getBoundingClientRect();if(r.right>b.left&&r.left<b.right&&r.bottom>b.top&&r.top<b.bottom){l.classList.add('done');next.classList.add('show')}})}
function setupStars(p){
  let n=0;
  const field=p.querySelector('#starfield'),line=p.querySelector('#starline'),stars=[...p.querySelectorAll('.star')],next=p.querySelector('#starNext'),doa=p.querySelector('.doa');
  const order=[0,1,2,3,4,5,6,0];
  const point=s=>{const r=s.getBoundingClientRect(),f=field.getBoundingClientRect();return{x:r.left-f.left+r.width/2,y:r.top-f.top+r.height/2}};
  const draw=(a,b)=>{
    const pa=point(stars[a]),pb=point(stars[b]);
    const el=document.createElementNS('http://www.w3.org/2000/svg','line');
    el.setAttribute('x1',pa.x);el.setAttribute('y1',pa.y);el.setAttribute('x2',pb.x);el.setAttribute('y2',pb.y);
    el.setAttribute('stroke','rgba(255,255,255,.95)');el.setAttribute('stroke-width','1.6');el.setAttribute('stroke-dasharray','4 5');el.setAttribute('stroke-linecap','round');
    el.classList.add('line-in');line.appendChild(el);
  };
  const wrong=s=>{s.classList.remove('wrong');void s.offsetWidth;s.classList.add('wrong');};
  stars.forEach((s,i)=>s.addEventListener('click',()=>{
    if(s.classList.contains('on'))return;
    const expected=order[n];
    if(i!==expected){wrong(s);doa.textContent='💗 Ikuti jalur love yaa';setTimeout(()=>{if(n<7)doa.textContent='⭐ '+n+'/7'},900);return;}
    s.classList.add('on');
    if(n>0)draw(order[n-1],i);
    n++;
    doa.textContent='⭐ '+n+'/7';
    if(n===7){
      draw(i,order[7]);
      next.classList.add('show');
    }
  }));
}
function setupHug(p){let n=0;const dog=p.querySelector('#hugdog'),done=p.querySelector('#hugdone');dog.addEventListener('click',()=>{n++;if(n>=3){dog.classList.add('near');done.classList.add('show');p.querySelector('#hugNext').classList.add('show')}else dog.style.left=(10+n*9)+'%'})}
const music=document.getElementById('music');function startMusic(){music.play().catch(()=>{})}document.body.addEventListener('click',e=>{if(e.target.closest('button,.dragFlower,.heart,.camera,.memory,.letter,.star,.hugdog'))startMusic()},{once:true});
document.getElementById('replay').addEventListener('click',()=>{location.reload()});
go(0);
